server:
  port: 80
  servlet:
    context-path: /small-api

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.105.183.83:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    #编码格式
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  # bucket名称
  bucket: "aip"
  # Minio服务地址
  host: "http://39.105.183.83:9000"
  # 访问路径
  url: "${minio.host}/${minio.bucket}/"
  # MINIO_ACCESS_KEY
  access-key: "minioadmin"
  # MINIO_SECRET_KEY
  secret-key: "minioadmin"



mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

logging:
  path: /Users/Administrator/Desktopims #日志文件路径
  file: ims.log #日志文件名称
  level:
    com:
      example: debug #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off